# Generated by Django 3.2.5 on 2022-01-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20220126_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lat',
            field=models.IntegerField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lng',
            field=models.IntegerField(default='', max_length=50),
        ),
    ]
