# Generated by Django 3.2.5 on 2022-01-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20220126_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
