# Generated by Django 3.2.5 on 2022-01-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20220128_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
