# Generated by Django 3.2.5 on 2022-01-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pickup_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
