# Generated by Django 3.2.5 on 2022-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pickups_active',
            field=models.BooleanField(default=False),
        ),
    ]
